import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

export interface EjercicioSeedData {
  nombre: string
  descripcion: string
  instrucciones: string
  grupoMuscular: "PECHO" | "ESPALDA" | "PIERNAS" | "HOMBROS" | "BRAZOS" | "CORE" | "CUERPO_COMPLETO"
  grupoMuscularSecundario?: string
  nivel: "PRINCIPIANTE" | "INTERMEDIO" | "AVANZADO"
  tipoEjercicio: "FUERZA" | "CARDIO" | "HIPERTROFIA" | "MOVILIDAD"
  equipamientoRequerido: "GIMNASIO_COMPLETO" | "MANCUERNAS_BANCOS" | "PESO_CORPORAL" | "BANDAS_RESISTENCIA" | "OTRO"
  restricciones?: string
  activo: boolean
}

export const CATALOGO_64_EJERCICIOS: EjercicioSeedData[] = [
  // ============================================================================
  // 1. PECHO (8 Ejercicios)
  // ============================================================================
  {
    nombre: "Press de Banca Plano con Barra",
    descripcion: "Ejercicio compuesto básico para el desarrollo de fuerza y masa en pectorales.",
    instrucciones: "Tumbado en banco plano, sujetar la barra a anchura superior a hombros, descender controlado al esternón y empujar con retracción escapular.",
    grupoMuscular: "PECHO",
    grupoMuscularSecundario: "TRICEPS, HOMBROS",
    nivel: "INTERMEDIO",
    tipoEjercicio: "FUERZA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Lesión de hombro o dolor en muñecas.",
    activo: true,
  },
  {
    nombre: "Press Plano con Mancuernas",
    descripcion: "Empuje bilateral con mancuernas que permite mayor rango de movimiento y trabajo estabilizador.",
    instrucciones: "En banco horizontal, descender las mancuernas a los laterales del pecho a 45-60 grados de abducción y empujar hasta extender brazos sin chocar mancuernas.",
    grupoMuscular: "PECHO",
    grupoMuscularSecundario: "TRICEPS, DELTOIDES_ANTERIOR",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "MANCUERNAS_BANCOS",
    restricciones: "Inestabilidad anterior de hombro.",
    activo: true,
  },
  {
    nombre: "Press Inclinado con Barra",
    descripcion: "Variante en banco inclinado a 30-45 grados con énfasis en la porción clavicular del pectoral.",
    instrucciones: "Banco inclinado a 30-45°, bajar la barra a la parte alta del pecho con codos en ángulo de 45° respecto al torso y empujar verticalmente.",
    grupoMuscular: "PECHO",
    grupoMuscularSecundario: "DELTOIDES_ANTERIOR, TRICEPS",
    nivel: "INTERMEDIO",
    tipoEjercicio: "FUERZA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Pinzamiento subacromial.",
    activo: true,
  },
  {
    nombre: "Press Inclinado con Mancuernas",
    descripcion: "Press inclinado que optimiza la activación de la porción clavicular con libertad articular.",
    instrucciones: "En banco a 30-45°, bajar mancuernas a la altura de la clavícula/pecho superior y empujar convergentemente.",
    grupoMuscular: "PECHO",
    grupoMuscularSecundario: "DELTOIDES_ANTERIOR, TRICEPS",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "MANCUERNAS_BANCOS",
    restricciones: "Molestias en deltoides anterior.",
    activo: true,
  },
  {
    nombre: "Press Declinado con Barra",
    descripcion: "Variante declinada con énfasis en las fibras inferiores y esternocostales del pectoral.",
    instrucciones: "Fijar piernas en banco declinado, descender la barra a la parte inferior del pecho y empujar con trayectoria perpendicular.",
    grupoMuscular: "PECHO",
    grupoMuscularSecundario: "TRICEPS",
    nivel: "INTERMEDIO",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Hipertensión no controlada o problemas de presión intraocular.",
    activo: true,
  },
  {
    nombre: "Aperturas con Mancuernas en Banco Plano",
    descripcion: "Ejercicio de aislamiento para estiramiento profundo del pectoral mayor.",
    instrucciones: "Tumbado en banco plano con codos ligeramente semiflexionados, abrir los brazos en arco hasta sentir estiramiento en el pecho y cerrar contrayendo.",
    grupoMuscular: "PECHO",
    grupoMuscularSecundario: "DELTOIDES_ANTERIOR",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "MANCUERNAS_BANCOS",
    restricciones: "Inestabilidad gleno-humeral anterior.",
    activo: true,
  },
  {
    nombre: "Cruces de Poleas Altas (Cable Crossover)",
    descripcion: "Aducción horizontal en polea alta con tensión constante en todo el recorrido.",
    instrucciones: "Torso ligeramente inclinado al frente, llevar los manerales hacia abajo y adelante cruzando ligeramente las manos al final de la contracción.",
    grupoMuscular: "PECHO",
    grupoMuscularSecundario: "DELTOIDES_ANTERIOR",
    nivel: "INTERMEDIO",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Molestia aguda en tendón bicipital o pectoral.",
    activo: true,
  },
  {
    nombre: "Flexiones de Pecho (Push-Ups)",
    descripcion: "Patrón fundamental de empuje horizontal en autocarga.",
    instrucciones: "Cuerpo en plancha recta alineada, descender el pecho hasta rozar el suelo con codos a 45° y empujar manteniendo el core firme.",
    grupoMuscular: "PECHO",
    grupoMuscularSecundario: "TRICEPS, CORE, HOMBROS",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "FUERZA",
    equipamientoRequerido: "PESO_CORPORAL",
    restricciones: "Dolor en muñecas (usar apoyos neutros).",
    activo: true,
  },

  // ============================================================================
  // 2. ESPALDA (8 Ejercicios)
  // ============================================================================
  {
    nombre: "Dominadas Pronas (Pull-Ups)",
    descripcion: "Tracción vertical completa con peso corporal para dorsal ancho y cintura escapular.",
    instrucciones: "Agarre prono más ancho que hombros, iniciar con depresión escapular y traccionar el cuerpo hasta que la barbilla supere la barra.",
    grupoMuscular: "ESPALDA",
    grupoMuscularSecundario: "BICEPS, CORE",
    nivel: "AVANZADO",
    tipoEjercicio: "FUERZA",
    equipamientoRequerido: "PESO_CORPORAL",
    restricciones: "Epicondilitis o lesión en manguito rotador.",
    activo: true,
  },
  {
    nombre: "Jalón al Pecho en Polea (Lat Pulldown)",
    descripcion: "Tracción vertical guiada ideal para progresión de fuerza y desarrollo dorsal.",
    instrucciones: "Sentado con muslos asegurados, tirar de la barra hacia la parte superior del esternón sacando pecho y retrayendo escápulas.",
    grupoMuscular: "ESPALDA",
    grupoMuscularSecundario: "BICEPS, ANTEBRAZOS",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Evitar jalones trasnuca por riesgo cervical.",
    activo: true,
  },
  {
    nombre: "Remo con Barra Inclinado (Bent-Over Row)",
    descripcion: "Tracción horizontal pesada para grosor de espalda media y fuerza postural.",
    instrucciones: "Torso inclinado a 45° con columna neutra, tirar de la barra hacia el ombligo manteniendo codos pegados al cuerpo.",
    grupoMuscular: "ESPALDA",
    grupoMuscularSecundario: "BICEPS, ERECTORES_ESPINALES, CORE",
    nivel: "INTERMEDIO",
    tipoEjercicio: "FUERZA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Hernia discal o lumbago agudo.",
    activo: true,
  },
  {
    nombre: "Remo con Mancuerna a una Mano (One-Arm DB Row)",
    descripcion: "Tracción unilateral con apoyo que minimiza la carga lumbar y corrige desbalances.",
    instrucciones: "Una rodilla y mano apoyadas en banco, traccionar la mancuerna hacia la cadera concentrando la contracción en el dorsal.",
    grupoMuscular: "ESPALDA",
    grupoMuscularSecundario: "BICEPS, CORE",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "MANCUERNAS_BANCOS",
    restricciones: "Rotación excesiva de tronco no recomendada.",
    activo: true,
  },
  {
    nombre: "Remo Sentado en Polea Baja (Seated Cable Row)",
    descripcion: "Remo horizontal con apoyo de pies para máxima estabilidad y trabajo de espalda media.",
    instrucciones: "Espalda erguida sin balanceo, tirar del agarre V hacia el abdomen bajo retrayendo las escápulas al final del recorrido.",
    grupoMuscular: "ESPALDA",
    grupoMuscularSecundario: "BICEPS, TRAPECIO_MEDIO",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Evitar hiperextensión lumbar descontrolada.",
    activo: true,
  },
  {
    nombre: "Remo en Barra T con Apoyo de Pecho",
    descripcion: "Remo con soporte torácico que anula el estrés en la zona lumbar baja.",
    instrucciones: "Apoyar el pecho en la almohadilla, agarrar las empuñaduras y traccionar llevando los codos hacia atrás con pausa isométrica.",
    grupoMuscular: "ESPALDA",
    grupoMuscularSecundario: "BICEPS, ROMBOIDES",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Molestias por presión esternal.",
    activo: true,
  },
  {
    nombre: "Pullover con Polea Alta (Brazos Rectos)",
    descripcion: "Aislamiento del dorsal ancho mediante extensión pura de hombro sin involucrar bíceps.",
    instrucciones: "De pie frente a la polea, brazos casi extendidos, descender la barra hacia los muslos contrayendo los dorsales.",
    grupoMuscular: "ESPALDA",
    grupoMuscularSecundario: "TRICEPS, CORE",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Molestia anterior en hombros al subir por encima de la cabeza.",
    activo: true,
  },
  {
    nombre: "Remo Invertido en Barra / TRX (Inverted Row)",
    descripcion: "Tracción horizontal en autocarga escalable para desarrollo de control escapular.",
    instrucciones: "Colgado bajo una barra fija con talones apoyados, traccionar el pecho hacia la barra manteniendo el cuerpo recto como una tabla.",
    grupoMuscular: "ESPALDA",
    grupoMuscularSecundario: "BICEPS, CORE",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "FUERZA",
    equipamientoRequerido: "PESO_CORPORAL",
    restricciones: "Falta de control postural (ajustar inclinación).",
    activo: true,
  },

  // ============================================================================
  // 3. HOMBROS (8 Ejercicios)
  // ============================================================================
  {
    nombre: "Press Militar con Barra de Pie (Overhead Press)",
    descripcion: "Patrón de empuje vertical puro con alta demanda de estabilidad de core y potencia deltoidea.",
    instrucciones: "De pie con glúteos y abdomen contraídos, empujar la barra verticalmente por encima de la cabeza con bloqueo activo.",
    grupoMuscular: "HOMBROS",
    grupoMuscularSecundario: "TRICEPS, CORE",
    nivel: "AVANZADO",
    tipoEjercicio: "FUERZA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Lumbalgia o pinzamiento subacromial.",
    activo: true,
  },
  {
    nombre: "Press Militar Sentado con Mancuernas",
    descripcion: "Empuje vertical con mancuernas en banco a 80-85° para máximo aislamiento deltoideo.",
    instrucciones: "Sentado con espalda apoyada, empujar mancuernas desde la altura de las orejas hacia arriba sin juntarlas violentamente.",
    grupoMuscular: "HOMBROS",
    grupoMuscularSecundario: "TRICEPS",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "MANCUERNAS_BANCOS",
    restricciones: "Dolor anterior de hombro.",
    activo: true,
  },
  {
    nombre: "Elevaciones Laterales con Mancuernas",
    descripcion: "Aislamiento del deltoides lateral para amplitud clavicular y aspecto redondeado.",
    instrucciones: "De pie con ligera inclinación al frente, elevar los brazos en plano escapular hasta la altura de los hombros con codos microflexionados.",
    grupoMuscular: "HOMBROS",
    grupoMuscularSecundario: "TRAPECIO",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "MANCUERNAS_BANCOS",
    restricciones: "Elevaciones por encima de 90° con cargas excesivas.",
    activo: true,
  },
  {
    nombre: "Elevaciones Laterales en Polea Baja",
    descripcion: "Elevación lateral unilateral con curva de resistencia constante desde el inicio del movimiento.",
    instrucciones: "De costado a la polea baja, traccionar el cable diagonalmente hacia el lateral hasta la horizontal con control excéntrico.",
    grupoMuscular: "HOMBROS",
    grupoMuscularSecundario: "TRAPECIO",
    nivel: "INTERMEDIO",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Molestias articulares en acromioclavicular.",
    activo: true,
  },
  {
    nombre: "Face Pull en Polea Alta",
    descripcion: "Ejercicio correctivo y de hipertrofia para deltoides posterior, rotadores externos y trapecio medio.",
    instrucciones: "Con cuerda en polea a la altura del rostro, traccionar hacia los ojos separando las manos y rotando los codos externamente.",
    grupoMuscular: "HOMBROS",
    grupoMuscularSecundario: "ESPALDA",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Pinzamiento severo de manguito rotador sin adaptación.",
    activo: true,
  },
  {
    nombre: "Pájaros con Mancuernas (Elevaciones Posteriores)",
    descripcion: "Aislamiento de deltoides posterior y romboides en posición inclinada.",
    instrucciones: "Torso flexionado paralelo al suelo o sobre banco inclinado, abrir los brazos hacia los laterales apretando la parte trasera del hombro.",
    grupoMuscular: "HOMBROS",
    grupoMuscularSecundario: "ESPALDA",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "MANCUERNAS_BANCOS",
    restricciones: "Sobrecarga cervical por hiperextensión del cuello.",
    activo: true,
  },
  {
    nombre: "Press Arnold con Mancuernas",
    descripcion: "Variante de press con rotación durante el ascenso que involucra deltoides anterior y lateral.",
    instrucciones: "Iniciar con palmas mirando al torso a la altura del pecho, girar las muñecas hacia afuera mientras se empuja hacia arriba.",
    grupoMuscular: "HOMBROS",
    grupoMuscularSecundario: "TRICEPS",
    nivel: "INTERMEDIO",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "MANCUERNAS_BANCOS",
    restricciones: "Molestias en rotadores de hombro.",
    activo: true,
  },
  {
    nombre: "Elevaciones Frontales con Disco o Mancuerna",
    descripcion: "Aislamiento de la porción anterior del deltoides en plano sagital.",
    instrucciones: "De pie, elevar el disco o mancuerna con brazos extendidos hasta la altura de la vista controlando la bajada.",
    grupoMuscular: "HOMBROS",
    grupoMuscularSecundario: "PECHO",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "MANCUERNAS_BANCOS",
    restricciones: "Evitar impulso o balanceo de columna.",
    activo: true,
  },

  // ============================================================================
  // 4. BÍCEPS (6 Ejercicios)
  // ============================================================================
  {
    nombre: "Curl de Bíceps con Barra de Pie",
    descripcion: "Ejercicio básico de flexión de codos para ganancia masiva de fuerza y volumen bicipital.",
    instrucciones: "De pie con codos fijos a los costados, flexionar los codos levantando la barra hasta la contracción máxima sin balancear el torso.",
    grupoMuscular: "BRAZOS",
    grupoMuscularSecundario: "ANTEBRAZOS",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "FUERZA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Dolor en muñecas (usar barra EZ si es necesario).",
    activo: true,
  },
  {
    nombre: "Curl Alterno con Mancuernas y Supinación",
    descripcion: "Curl que combina flexión y supinación de antebrazo para activación biarticular del bíceps.",
    instrucciones: "Comenzar en agarre neutro y rotar la palma hacia arriba durante la subida, apretando 1 segundo en el punto alto.",
    grupoMuscular: "BRAZOS",
    grupoMuscularSecundario: "ANTEBRAZOS",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "MANCUERNAS_BANCOS",
    restricciones: "Tendinopatía bicipital distal.",
    activo: true,
  },
  {
    nombre: "Curl en Banco Scott (Predicador) con Barra EZ",
    descripcion: "Aislamiento estricto que anula cualquier inercia corporal y enfatiza el pico del bíceps.",
    instrucciones: "Brazos apoyados en la almohadilla inclinada, descender la barra hasta casi extensión completa y flexionar con fuerza.",
    grupoMuscular: "BRAZOS",
    grupoMuscularSecundario: "ANTEBRAZOS",
    nivel: "INTERMEDIO",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Evitar hiperextensión brusca en la fase inferior.",
    activo: true,
  },
  {
    nombre: "Curl Martillo con Mancuernas (Hammer Curl)",
    descripcion: "Flexión con agarre neutro que enfatiza el braquial anterior y braquiorradial.",
    instrucciones: "Mantener las palmas enfrentadas durante todo el recorrido, subiendo de forma simultánea o alterna.",
    grupoMuscular: "BRAZOS",
    grupoMuscularSecundario: "ANTEBRAZOS",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "MANCUERNAS_BANCOS",
    restricciones: "Molestias en epicóndilo lateral.",
    activo: true,
  },
  {
    nombre: "Curl Inclinado con Mancuernas en Banco",
    descripcion: "Curl en banco a 45-60° que pone la cabeza larga del bíceps en máximo estiramiento.",
    instrucciones: "Sentado en banco reclinado con los brazos colgando verticalmente, flexionar sin adelantar los codos.",
    grupoMuscular: "BRAZOS",
    grupoMuscularSecundario: "ANTEBRAZOS",
    nivel: "INTERMEDIO",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "MANCUERNAS_BANCOS",
    restricciones: "Sensibilidad en la porción anterior del hombro.",
    activo: true,
  },
  {
    nombre: "Curl en Polea Alta (Doble Bíceps / Spider Cable)",
    descripcion: "Flexión en abducción de hombro en torre de poleas para contracción en acortamiento máximo.",
    instrucciones: "De pie en el centro de dos poleas altas, flexionar los codos llevando los manerales hacia la cabeza manteniendo codos a la altura de los hombros.",
    grupoMuscular: "BRAZOS",
    grupoMuscularSecundario: "ANTEBRAZOS",
    nivel: "INTERMEDIO",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Inestabilidad articular en hombros.",
    activo: true,
  },

  // ============================================================================
  // 5. TRÍCEPS (6 Ejercicios)
  // ============================================================================
  {
    nombre: "Press de Banca con Agarre Cerrado",
    descripcion: "Empuje compuesto pesado con manos a la anchura de hombros para sobrecarga máxima de tríceps.",
    instrucciones: "Tumbado en banco, agarrar la barra a anchura de hombros, bajar con codos pegados al cuerpo y empujar verticalmente.",
    grupoMuscular: "BRAZOS",
    grupoMuscularSecundario: "PECHO, HOMBROS",
    nivel: "INTERMEDIO",
    tipoEjercicio: "FUERZA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Molestias en muñecas con agarres excesivamente estrechos.",
    activo: true,
  },
  {
    nombre: "Fondos en Paralelas para Tríceps (Dips)",
    descripcion: "Extensión en barras paralelas con torso vertical para máximo trabajo de tríceps.",
    instrucciones: "Sujetarse en barras paralelas, mantener el cuerpo erguido, descender hasta que los codos formen 90° y extender con potencia.",
    grupoMuscular: "BRAZOS",
    grupoMuscularSecundario: "PECHO, HOMBROS",
    nivel: "AVANZADO",
    tipoEjercicio: "FUERZA",
    equipamientoRequerido: "PESO_CORPORAL",
    restricciones: "Pinzamiento o inestabilidad anterior de hombro.",
    activo: true,
  },
  {
    nombre: "Extensiones de Tríceps en Polea Alta con Cuerda (Pushdown)",
    descripcion: "Aislamiento de tríceps con separación de cuerda al final para activar la cabeza lateral.",
    instrucciones: "Codos pegados a los costados, extender los brazos hacia abajo y separar los extremos de la cuerda al final de la contracción.",
    grupoMuscular: "BRAZOS",
    grupoMuscularSecundario: "ANTEBRAZOS",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Tendinitis en el tendón del tríceps.",
    activo: true,
  },
  {
    nombre: "Press Francés con Barra EZ en Banco Plano (Skull Crushers)",
    descripcion: "Extensión acostada de codos que enfatiza la cabeza larga y media del tríceps.",
    instrucciones: "Tumbado en banco, sujetar barra EZ con brazos verticales, flexionar codos llevando la barra hacia la frente y extender controladamente.",
    grupoMuscular: "BRAZOS",
    grupoMuscularSecundario: "ANTEBRAZOS",
    nivel: "INTERMEDIO",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Dolor en articulación del codo.",
    activo: true,
  },
  {
    nombre: "Extensión de Tríceps sobre la Cabeza con Mancuerna (Copa)",
    descripcion: "Extensión vertical unilateral o bilateral para máximo estiramiento de la cabeza larga.",
    instrucciones: "Sentado, sostener una mancuerna con ambas manos por detrás de la cabeza, extender los codos hacia arriba manteniendo brazos pegados a las orejas.",
    grupoMuscular: "BRAZOS",
    grupoMuscularSecundario: "HOMBROS",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "MANCUERNAS_BANCOS",
    restricciones: "Limitación de movilidad en flexión de hombros.",
    activo: true,
  },
  {
    nombre: "Fondos entre Bancos (Bench Dips)",
    descripcion: "Variante accesible de fondos con apoyo de manos y talones sobre bancos.",
    instrucciones: "Manos apoyadas al borde de un banco, pies al frente en el suelo u otro banco, flexionar codos hasta 90° y empujar hacia arriba.",
    grupoMuscular: "BRAZOS",
    grupoMuscularSecundario: "PECHO, HOMBROS",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "FUERZA",
    equipamientoRequerido: "MANCUERNAS_BANCOS",
    restricciones: "Evitar descender excesivamente para proteger cápsula articular anterior.",
    activo: true,
  },

  // ============================================================================
  // 6. PIERNAS / CUÁDRICEPS & ISQUIOSURALES (10 Ejercicios)
  // ============================================================================
  {
    nombre: "Sentadilla Trasera con Barra (Back Squat)",
    descripcion: "Rey de los ejercicios de pierna para fuerza global, cuádriceps, glúteos y cadena posterior.",
    instrucciones: "Barra apoyada en trapecios, pies al ancho de hombros, descender rompiendo el paralelo con cadera y rodillas, empujar manteniendo el pecho erguido.",
    grupoMuscular: "PIERNAS",
    grupoMuscularSecundario: "GLUTEOS, CORE",
    nivel: "AVANZADO",
    tipoEjercicio: "FUERZA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Artrosis femororrotuliana severa o hernia lumbar aguda.",
    activo: true,
  },
  {
    nombre: "Sentadilla Frontal con Barra (Front Squat)",
    descripcion: "Sentadilla con carga frontal que maximiza la verticalidad del torso y la activación del cuádriceps.",
    instrucciones: "Barra apoyada en deltoides anteriores con codos altos, descender profundo manteniendo el torso totalmente recto.",
    grupoMuscular: "PIERNAS",
    grupoMuscularSecundario: "CORE, GLUTEOS",
    nivel: "AVANZADO",
    tipoEjercicio: "FUERZA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Movilidad deficiente en dorsiflexión de tobillo o muñecas.",
    activo: true,
  },
  {
    nombre: "Prensa de Piernas Inclinada a 45° (Leg Press)",
    descripcion: "Empuje de piernas en máquina con respaldo que permite mover grandes cargas sin estrés en la columna.",
    instrucciones: "Espalda firmemente apoyada, pies a anchura de hombros en plataforma, descender hasta 90° de flexión de rodillas y empujar sin bloquear articulaciones.",
    grupoMuscular: "PIERNAS",
    grupoMuscularSecundario: "GLUTEOS",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Despegue de la pelvis del respaldo durante la bajada (retroversión pélvica).",
    activo: true,
  },
  {
    nombre: "Extensiones de Cuádriceps en Máquina (Leg Extension)",
    descripcion: "Aislamiento puro del cuádriceps en cadena cinética abierta con tensión máxima en extensión.",
    instrucciones: "Sentado con rodillas alineadas al eje de giro de la máquina, extender las piernas hasta la horizontal, pausar 1 segundo y bajar lento.",
    grupoMuscular: "PIERNAS",
    grupoMuscularSecundario: "CORE",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Condromalacia rotuliana o postoperatorio de ligamento cruzado.",
    activo: true,
  },
  {
    nombre: "Zancadas / Desplantes Caminando (Walking Lunges)",
    descripcion: "Ejercicio unilateral dinámico para fuerza funcional de cuádriceps, glúteos y equilibrio.",
    instrucciones: "Avanzar dando un paso amplio, descender la rodilla trasera hacia el suelo sin tocarlo y empujar con la pierna delantera hacia el siguiente paso.",
    grupoMuscular: "PIERNAS",
    grupoMuscularSecundario: "GLUTEOS, CORE",
    nivel: "INTERMEDIO",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "MANCUERNAS_BANCOS",
    restricciones: "Inestabilidad de rodilla o dolor patelar en impacto.",
    activo: true,
  },
  {
    nombre: "Sentadilla Búlgara con Mancuernas (Bulgarian Split Squat)",
    descripcion: "Sentadilla unilateral con pie trasero elevado que proporciona altísima estimulación neuromuscular.",
    instrucciones: "Pie trasero apoyado en banco, descender en vertical hasta que el muslo delantero quede paralelo al suelo y empujar a través del talón.",
    grupoMuscular: "PIERNAS",
    grupoMuscularSecundario: "GLUTEOS, CORE",
    nivel: "INTERMEDIO",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "MANCUERNAS_BANCOS",
    restricciones: "Acortamiento severo del psoas ilíaco o falta de equilibrio.",
    activo: true,
  },
  {
    nombre: "Peso Muerto Rumano con Barra (RDL)",
    descripcion: "Bisagra de cadera fundamental para estiramiento y sobrecarga excéntrica de isquiosurales.",
    instrucciones: "Rodillas semiflexionadas fijas, empujar la cadera hacia atrás deslizando la barra por los muslos hasta sentir tensión en isquios, y volver contrayendo glúteos.",
    grupoMuscular: "PIERNAS",
    grupoMuscularSecundario: "GLUTEOS, ESPALDA, CORE",
    nivel: "INTERMEDIO",
    tipoEjercicio: "FUERZA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Flexión lumbar compensatoria.",
    activo: true,
  },
  {
    nombre: "Curl Femoral Tumbado en Máquina (Lying Leg Curl)",
    descripcion: "Flexión de rodilla en decúbito prono para aislamiento directo de los isquiosurales.",
    instrucciones: "Tumbado boca abajo, flexionar las rodillas acercando el rodillo a los glúteos manteniendo la pelvis pegada al banco.",
    grupoMuscular: "PIERNAS",
    grupoMuscularSecundario: "PANTORRILLAS",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Calambres recurrentes en isquiosurales.",
    activo: true,
  },
  {
    nombre: "Curl Femoral Sentado en Máquina (Seated Leg Curl)",
    descripcion: "Flexión de rodilla con cadera flexionada, colocando los isquiosurales en mayor longitud muscular.",
    instrucciones: "Sentado con muslos sujetos por la almohadilla, flexionar las piernas hacia abajo y atrás apretando en la parte final.",
    grupoMuscular: "PIERNAS",
    grupoMuscularSecundario: "PANTORRILLAS",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Acortamiento severo de la cadena posterior.",
    activo: true,
  },
  {
    nombre: "Elevación de Talones de Pie en Máquina (Calf Raises)",
    descripcion: "Extensión de tobillo con rodillas extendidas para máximo trabajo del gastrocnemio (gemelos).",
    instrucciones: "Apoyar la punta de los pies en el escalón, descender los talones para estiramiento completo y subir a la máxima contracción sobre las puntas.",
    grupoMuscular: "PIERNAS",
    grupoMuscularSecundario: "PANTORRILLAS",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Tendinopatía aquilea en fase aguda.",
    activo: true,
  },

  // ============================================================================
  // 7. GLÚTEOS (6 Ejercicios)
  // ============================================================================
  {
    nombre: "Hip Thrust con Barra en Banco",
    descripcion: "Ejercicio de empuje de cadera horizontal considerado el estándar de oro para hipertrofia del glúteo mayor.",
    instrucciones: "Espalda alta apoyada en banco, barra acolchada sobre la pelvis, empujar con los talones hasta alinear torso y muslos apretando los glúteos 2 segundos.",
    grupoMuscular: "PIERNAS",
    grupoMuscularSecundario: "GLUTEOS, CORE",
    nivel: "INTERMEDIO",
    tipoEjercicio: "FUERZA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Molestias por apoyo pélvico (usar acolchado grueso).",
    activo: true,
  },
  {
    nombre: "Puente de Glúteos en Suelo con Mancuerna o Disco (Glute Bridge)",
    descripcion: "Extensión de cadera en decúbito supino para activación neuromuscular directa del glúteo.",
    instrucciones: "Tumbado boca arriba con rodillas flexionadas y pies en el suelo, elevar la pelvis apretando glúteos arriba sin arquear la zona lumbar.",
    grupoMuscular: "PIERNAS",
    grupoMuscularSecundario: "GLUTEOS, CORE",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "MANCUERNAS_BANCOS",
    restricciones: "Hiperextensión lumbar.",
    activo: true,
  },
  {
    nombre: "Patada de Glúteo en Polea Baja (Cable Kickback)",
    descripcion: "Extensión pura de cadera en polea con tobillera para trabajo analítico del glúteo mayor.",
    instrucciones: "Torso inclinado apoyado en la torre, extender la pierna hacia atrás y ligeramente hacia afuera contrayendo el glúteo sin girar la pelvis.",
    grupoMuscular: "PIERNAS",
    grupoMuscularSecundario: "GLUTEOS",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Balanceo lumbar con cargas excesivas.",
    activo: true,
  },
  {
    nombre: "Abducción de Cadera en Máquina (Seated Hip Abduction)",
    descripcion: "Aislamiento en máquina para desarrollo del glúteo medio y menor, clave en estabilidad pélvica.",
    instrucciones: "Sentado con almohadillas en la cara externa de los muslos, abrir las piernas al máximo, pausar 1 segundo y cerrar con control.",
    grupoMuscular: "PIERNAS",
    grupoMuscularSecundario: "GLUTEOS",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Bursitis trocantérica en fase aguda.",
    activo: true,
  },
  {
    nombre: "Paseos con Banda Elástica en Tobillos (Monster Walk)",
    descripcion: "Activación dinámica y continua de abductores y rotadores externos de cadera con minifoot band.",
    instrucciones: "En posición de media sentadilla con banda en tobillos o rodillas, dar pasos laterales o en diagonal manteniendo tensión constante.",
    grupoMuscular: "PIERNAS",
    grupoMuscularSecundario: "GLUTEOS, CORE",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "MOVILIDAD",
    equipamientoRequerido: "BANDAS_RESISTENCIA",
    restricciones: "Colapso medial de rodillas (valgo dinámico).",
    activo: true,
  },
  {
    nombre: "Step-Up en Banco con Mancuernas",
    descripcion: "Subida a cajón o banco para trabajo unilateral de glúteo y cuádriceps sin impacto.",
    instrucciones: "Colocar un pie en el banco, empujar únicamente con esa pierna para elevar el cuerpo sin impulsarse con la pierna del suelo.",
    grupoMuscular: "PIERNAS",
    grupoMuscularSecundario: "GLUTEOS, CORE",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "FUERZA",
    equipamientoRequerido: "MANCUERNAS_BANCOS",
    restricciones: "Inestabilidad o altura de banco excesiva para la movilidad de cadera.",
    activo: true,
  },

  // ============================================================================
  // 8. CORE (8 Ejercicios)
  // ============================================================================
  {
    nombre: "Plancha Abdominal Frontal Isométrica (Plank)",
    descripcion: "Estabilización isométrica anti-extensión fundamental para la pared abdominal profunda y transverso.",
    instrucciones: "Apoyado sobre antebrazos y puntas de pies, alinear cabeza, tronco y talones contrayendo abdomen y glúteos sin dejar caer la cadera.",
    grupoMuscular: "CORE",
    grupoMuscularSecundario: "HOMBROS, GLUTEOS",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "FUERZA",
    equipamientoRequerido: "PESO_CORPORAL",
    restricciones: "Lumbalgia por arqueamiento de espalda baja.",
    activo: true,
  },
  {
    nombre: "Plancha Lateral (Side Plank)",
    descripcion: "Estabilidad anti-flexión lateral que activa intensamente el cuadrado lumbar y oblicuos.",
    instrucciones: "Apoyado sobre un antebrazo de costado, elevar la pelvis hasta formar una línea recta con el cuerpo, manteniendo la posición.",
    grupoMuscular: "CORE",
    grupoMuscularSecundario: "HOMBROS, GLUTEOS",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "FUERZA",
    equipamientoRequerido: "PESO_CORPORAL",
    restricciones: "Dolor agudo en articulación del hombro de apoyo.",
    activo: true,
  },
  {
    nombre: "Rueda Abdominal (Ab Wheel Rollout)",
    descripcion: "Ejercicio de alta intensidad anti-extensión para toda la musculatura del tronco.",
    instrucciones: "De rodillas, rodar la rueda hacia adelante extendiendo el cuerpo hasta el límite de control y regresar traccionando desde el abdomen.",
    grupoMuscular: "CORE",
    grupoMuscularSecundario: "ESPALDA, HOMBROS",
    nivel: "AVANZADO",
    tipoEjercicio: "FUERZA",
    equipamientoRequerido: "PESO_CORPORAL",
    restricciones: "Patología discal lumbar o falta de fuerza de base en plancha.",
    activo: true,
  },
  {
    nombre: "Dead Bug (Bicho Muerto)",
    descripcion: "Ejercicio de disociación lumbopélvica y control postural sin estrés articular.",
    instrucciones: "Boca arriba con espalda baja pegada al suelo, extender brazo y pierna opuestos simultáneamente de forma lenta y controlada.",
    grupoMuscular: "CORE",
    grupoMuscularSecundario: "HOMBROS, PIERNAS",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "MOVILIDAD",
    equipamientoRequerido: "PESO_CORPORAL",
    restricciones: "Despegue de la zona lumbar del suelo durante la extensión.",
    activo: true,
  },
  {
    nombre: "Bird-Dog (Pájaro-Perro)",
    descripcion: "Estabilidad cruzada de la columna y activación de erectores espinales del modelo McGill.",
    instrucciones: "En cuatro apoyos, extender un brazo y la pierna contraria hasta la horizontal, sostener 3 segundos y alternar con control postural.",
    grupoMuscular: "CORE",
    grupoMuscularSecundario: "ESPALDA, GLUTEOS",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "MOVILIDAD",
    equipamientoRequerido: "PESO_CORPORAL",
    restricciones: "Dolor en muñecas o rodillas en apoyo estático.",
    activo: true,
  },
  {
    nombre: "Elevaciones de Piernas Colgado en Barra (Hanging Leg Raise)",
    descripcion: "Flexión de cadera y columna en suspensión para desarrollo del recto abdominal inferior.",
    instrucciones: "Colgado de una barra con agarre prono, elevar las piernas rectas o flexionadas hacia el pecho realizando retroversión pélvica sin balanceo.",
    grupoMuscular: "CORE",
    grupoMuscularSecundario: "ANTEBRAZOS, PIERNAS",
    nivel: "AVANZADO",
    tipoEjercicio: "FUERZA",
    equipamientoRequerido: "PESO_CORPORAL",
    restricciones: "Acortamiento severo de isquiotibiales o debilidad de agarre.",
    activo: true,
  },
  {
    nombre: "Crunch en Polea Alta con Cuerda (Cable Crunch)",
    descripcion: "Flexión espinal con carga ajustable para sobrecarga progresiva del recto del abdomen.",
    instrucciones: "De rodillas frente a la polea, sujetar la cuerda junto a las sienes y flexionar el tronco acercando los codos a los muslos contrayendo el abdomen.",
    grupoMuscular: "CORE",
    grupoMuscularSecundario: "ESPALDA",
    nivel: "INTERMEDIO",
    tipoEjercicio: "HIPERTROFIA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Hernia discal lumbar sintomática en flexión.",
    activo: true,
  },
  {
    nombre: "Pallof Press en Polea o Banda",
    descripcion: "Patrón fundamental de anti-rotación para estabilidad central y control oblicuo.",
    instrucciones: "De pie perpendicular a la polea, sostener el cable a la altura del pecho y extender los brazos al frente resistiendo la fuerza de giro.",
    grupoMuscular: "CORE",
    grupoMuscularSecundario: "HOMBROS",
    nivel: "PRINCIPIANTE",
    tipoEjercicio: "FUERZA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Rotación compensatoria de pelvis o columna.",
    activo: true,
  },

  // ============================================================================
  // 9. CUERPO COMPLETO / FUNCIONAL (4 Ejercicios)
  // ============================================================================
  {
    nombre: "Peso Muerto Convencional con Barra (Deadlift)",
    descripcion: "Levantamiento total de fuerza máxima para toda la cadena posterior y el cuerpo completo.",
    instrucciones: "Barra sobre la mitad del pie, agarre firme por fuera de las piernas, extender rodillas y cadera al unísono manteniendo la columna neutra.",
    grupoMuscular: "CUERPO_COMPLETO",
    grupoMuscularSecundario: "PIERNAS, ESPALDA, CORE",
    nivel: "AVANZADO",
    tipoEjercicio: "FUERZA",
    equipamientoRequerido: "GIMNASIO_COMPLETO",
    restricciones: "Hernia discal lumbar o inestabilidad espinal activa.",
    activo: true,
  },
  {
    nombre: "Farmer’s Walk (Paseo del Granjero)",
    descripcion: "Transporte de carga pesada bilateral que potencia el agarre, la postura erguida y la estabilidad del core.",
    instrucciones: "Sostener una mancuerna pesada en cada mano, caminar con pasos cortos y firmes manteniendo hombros atrás y columna perfectamente vertical.",
    grupoMuscular: "CUERPO_COMPLETO",
    grupoMuscularSecundario: "CORE, BRAZOS, PIERNAS",
    nivel: "INTERMEDIO",
    tipoEjercicio: "FUERZA",
    equipamientoRequerido: "MANCUERNAS_BANCOS",
    restricciones: "Pinzamiento o inestabilidad lumbar aguda.",
    activo: true,
  },
  {
    nombre: "Kettlebell Swing / Balanceo con Pesa Rusa",
    descripcion: "Movimiento balístico de bisagra de cadera para potencia de glúteos y acondicionamiento metabólico.",
    instrucciones: "Flexionar cadera llevando la pesa entre las piernas y proyectarla hacia adelante hasta la altura del pecho mediante una potente extensión de glúteos.",
    grupoMuscular: "CUERPO_COMPLETO",
    grupoMuscularSecundario: "GLUTEOS, PIERNAS, CORE",
    nivel: "INTERMEDIO",
    tipoEjercicio: "CARDIO",
    equipamientoRequerido: "MANCUERNAS_BANCOS",
    restricciones: "Flexión lumbar en la parte baja del swing.",
    activo: true,
  },
  {
    nombre: "Burpees con Salto",
    descripcion: "Ejercicio calisténico continuo de alta demanda cardiovascular y coordinación motora.",
    instrucciones: "Desde posición de pie, agacharse, apoyar manos en el suelo, extender piernas a plancha, hacer una flexión, recoger piernas y saltar verticalmente.",
    grupoMuscular: "CUERPO_COMPLETO",
    grupoMuscularSecundario: "PECHO, PIERNAS, CORE",
    nivel: "INTERMEDIO",
    tipoEjercicio: "CARDIO",
    equipamientoRequerido: "PESO_CORPORAL",
    restricciones: "Problemas articulares en muñecas o rodillas por impacto.",
    activo: true,
  },
]

export async function seedEjercicios() {
  console.log("==================================================================")
  console.log("MR. GYM — SEED DE CATÁLOGO DE EJERCICIOS (64 EJERCICIOS)")
  console.log("==================================================================\n")

  const totalAntes = await prisma.ejercicio.count()
  console.log(`Estado inicial: ${totalAntes} ejercicios registrados en la base de datos.`)

  let creados = 0
  let actualizados = 0

  for (const ej of CATALOGO_64_EJERCICIOS) {
    const existing = await prisma.ejercicio.findUnique({
      where: { nombre: ej.nombre },
    })

    await prisma.ejercicio.upsert({
      where: { nombre: ej.nombre },
      update: {
        descripcion: ej.descripcion,
        instrucciones: ej.instrucciones,
        grupoMuscular: ej.grupoMuscular,
        grupoMuscularSecundario: ej.grupoMuscularSecundario || null,
        nivel: ej.nivel,
        tipoEjercicio: ej.tipoEjercicio,
        equipamientoRequerido: ej.equipamientoRequerido,
        restricciones: ej.restricciones || null,
        activo: ej.activo,
      },
      create: {
        nombre: ej.nombre,
        descripcion: ej.descripcion,
        instrucciones: ej.instrucciones,
        grupoMuscular: ej.grupoMuscular,
        grupoMuscularSecundario: ej.grupoMuscularSecundario || null,
        nivel: ej.nivel,
        tipoEjercicio: ej.tipoEjercicio,
        equipamientoRequerido: ej.equipamientoRequerido,
        restricciones: ej.restricciones || null,
        activo: ej.activo,
      },
    })

    if (existing) {
      actualizados++
    } else {
      creados++
    }
  }

  const totalDespues = await prisma.ejercicio.count()

  console.log(`\nResultados del Seed:`)
  console.log(`- Ejercicios nuevos insertados: ${creados}`)
  console.log(`- Ejercicios actualizados/revalidados: ${actualizados}`)
  console.log(`- Total final en catálogo: ${totalDespues} ejercicios`)

  return { totalAntes, creados, actualizados, totalDespues }
}

if (require.main === module) {
  seedEjercicios()
    .then(() => prisma.$disconnect())
    .catch((e) => {
      console.error("Error al ejecutar seed de ejercicios:", e)
      prisma.$disconnect()
      process.exit(1)
    })
}
